-- ═══════════════════════════════════════════════════════════
-- Migration 002 — Narrator Layer (fleet-narrator Worker)
-- Adds tables for caption gap analysis & suggestion tracking.
-- Run AFTER 001 (fleet.sql).
-- ═══════════════════════════════════════════════════════════

-- ── Narrator Reports ───────────────────────────────────────
-- One row per analysis run (cron or manual).
CREATE TABLE IF NOT EXISTS narrator_reports (
  id                          TEXT PRIMARY KEY,
  generated_at                TEXT NOT NULL,
  period_start                TEXT NOT NULL,    -- earliest capture analyzed
  period_end                  TEXT NOT NULL,    -- latest capture analyzed
  trigger_type                TEXT NOT NULL,    -- 'cron' | 'manual'
  total_captures              INTEGER DEFAULT 0,
  aligned_pairs               INTEGER DEFAULT 0,
  gaps_found                  INTEGER DEFAULT 0,
  suggestions_generated       INTEGER DEFAULT 0,
  avg_captain_coverage        REAL,             -- % of captain terms machine uses (0..1)
  avg_caption_length_delta    INTEGER,          -- avg(captain_len - machine_len)
  avg_alignment_score         REAL,             -- avg cosine sim of paired (embeddings)
  status                      TEXT,             -- 'running' | 'completed' | 'failed'
  error_message               TEXT,
  duration_ms                 INTEGER,
  created_at                  TEXT DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_reports_gen    ON narrator_reports(generated_at);
CREATE INDEX IF NOT EXISTS idx_reports_status ON narrator_reports(status);

-- ── Caption Gaps ───────────────────────────────────────────
-- Each row = one systematic mismatch between machine captions and captain text.
-- e.g. "machine never says 'tight school'" / "machine says 'blob count', captain never does"
CREATE TABLE IF NOT EXISTS caption_gaps (
  id                          TEXT PRIMARY KEY,
  report_id                   TEXT NOT NULL,
  gap_type                    TEXT NOT NULL,    -- 'captain_only_term' | 'machine_only_term' | 'temporal_reference' | 'qualitative_judgment' | 'context_missing' | 'numeric_overload'
  pattern                     TEXT NOT NULL,    -- e.g. 'tight school', 'blob count', 'same school as last pass'
  -- Frequency stats
  frequency_pct               REAL,            -- share of aligned pairs where pattern appears in source side
  captain_frequency           REAL,            -- 0..1 of captain-side text containing pattern
  machine_frequency           REAL,            -- 0..1 of machine-side caption containing pattern
  evidence_count              INTEGER,         -- supporting aligned pairs
  -- Severity
  severity                    REAL,            -- 0..1, computed from frequency + clarity
  -- Examples
  example_capture_id          TEXT,
  example_captain_text        TEXT,
  example_machine_caption     TEXT,
  -- Resolution
  suggestion                  TEXT NOT NULL,   -- human-readable fix description
  template                    TEXT,            -- suggested caption-template fragment
  -- Metadata
  metadata                    TEXT DEFAULT '{}',  -- JSON: {bigram, zone, etc.}
  created_at                  TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (report_id) REFERENCES narrator_reports(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_gaps_report   ON caption_gaps(report_id);
CREATE INDEX IF NOT EXISTS idx_gaps_type     ON caption_gaps(gap_type);
CREATE INDEX IF NOT EXISTS idx_gaps_severity ON caption_gaps(severity DESC);

-- ── Caption Suggestions ────────────────────────────────────
-- Improved captions generated by the narrator for individual captures.
CREATE TABLE IF NOT EXISTS caption_suggestions (
  id                          TEXT PRIMARY KEY,
  report_id                   TEXT NOT NULL,
  capture_id                  TEXT NOT NULL,
  gap_id                      TEXT,             -- optional FK: which gap this addresses
  original_caption            TEXT,
  suggested_caption           TEXT NOT NULL,
  rationale                   TEXT,             -- why this caption is better
  model                       TEXT,             -- which generator produced it: 'template' | '@cf/...'
  applied                     INTEGER DEFAULT 0,        -- shipped to analyzer
  captain_confirmed           INTEGER DEFAULT 0,        -- captain feedback
  captain_correction          TEXT,                     -- what captain changed it to
  created_at                  TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (report_id)  REFERENCES narrator_reports(id)   ON DELETE CASCADE,
  FOREIGN KEY (capture_id) REFERENCES captures(capture_id),
  FOREIGN KEY (gap_id)     REFERENCES caption_gaps(id)      ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_sug_report   ON caption_suggestions(report_id);
CREATE INDEX IF NOT EXISTS idx_sug_capture  ON caption_suggestions(capture_id);
CREATE INDEX IF NOT EXISTS idx_sug_applied  ON caption_suggestions(applied);
CREATE INDEX IF NOT EXISTS idx_sug_confirmed ON caption_suggestions(captain_confirmed);

-- ── A2A activity log (polyformalism) ───────────────────────
-- Reuse existing a2a_messages table. Narrator sends intents to:
--   - 'fleet-analyzer' (apply suggestions)
--   - 'fleet-vocabulary' (new species heuristics)
--   - 'fleet-dashboard' (publish report summary)
